-- Create n8n database and user
CREATE DATABASE n8n;
CREATE USER n8n WITH ENCRYPTED PASSWORD 'n8n';
GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n;
ALTER DATABASE n8n OWNER TO n8n;

-- Create langflow database and user
CREATE DATABASE langflow;
CREATE USER langflow WITH ENCRYPTED PASSWORD 'langflow';
GRANT ALL PRIVILEGES ON DATABASE langflow TO langflow;
ALTER DATABASE langflow OWNER TO langflow;

